name: Beautifier

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main , reLint ]

jobs:
  beautify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run beautysh
        uses: illvart/beautysh-action@latest
        with:
          # Pass beautysh options in args, for example:
          args: '*msalm.sh --indent-size 5 --force-function-style paronly'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[auto] ci: apply beautysh changes'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
